using System;
using System.Collections.Generic;
using System.Text;

namespace Daddoon.Blazor.Xam.InteropApp.Common
{
    public class DummyClass
    {
        public const string Lorem = @"IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem IpsumDolorem ";
    }
}
