using System;
using System.Collections.Generic;
using System.Text;

namespace BlazorMobile.Proxy
{
    public static class Resource
    {
        public const string ObsoleteMessage = "This class was auto-generated by BlazorMobile and is for internal use only";

        public const string NonAsyncMethodNotSupported = "Non-async methods are not supported when calling to native. You must use the Task or Task<> return type on your methods signature";
    }
}
