
using BlazorMobile.Components;
using BlazorMobile.Helper;
using Org.Mozilla.Geckoview;
using System;

namespace BlazorMobile.Droid.Helper
{
    internal static class WebExtensionHelper
    {
        private static int _counter = 0;

        private static int GenerateWebExtensionIdentity()
        {
            return _counter++;
        }

        /// <summary>
        /// Register the given WebExtension to the given runtime instance of a GeckoView
        /// This method is used to forward event based on WebExtension id to the right GeckoView instance
        /// The WebExtension id will be generated by this method
        /// </summary>
        internal static void RegisterWebExtension(BlazorGeckoView blazorGeckoView, GeckoRuntime runtime, string webExtensionLocation)
        {
            if (blazorGeckoView == null)
            {
                throw new ArgumentNullException(nameof(blazorGeckoView));
            }

            //Get an unique identity
            int identity = GenerateWebExtensionIdentity();

            //Register the given WebExtension to the runtime
            runtime.RegisterWebExtension(new WebExtension(webExtensionLocation, identity.ToString()));

            //Register the Webview with this identity attached to retrieve it later by WebExtension identity
            WebViewHelper.RegisterWebView(blazorGeckoView, identity);
        }
    }
}